version: '3.2'

services:
  app:
    build: .
    image: fmudrunek/github-slack-pr-notifier
    volumes:
      - type: bind
        source: ${PATH_TO_CONFIG}
        target: /config.json
        read_only: true
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - SLACK_BEARER_TOKEN=${SLACK_BEARER_TOKEN}
    entrypoint: [python3, runner.py]


