version: '3.2'

services:
  app:
    build: .
    image: fmudrunek/github-slack-pr-notifier
    volumes:
      - type: bind
        source: ./resources/config.json
        target: /app/resources/config.json
        read_only: true
    env_file:
      - .env
