version: '3.2'

services:
  app:
    build: .
    image: fmudrunek/github-slack-pr-notifier
    volumes:
      - type: bind
        source: ./${PATH_TO_CONFIG}
        target: /src/resources/config.json
        read_only: true
    environment:
      - GITHUB_BASE_URL=${GITHUB_BASE_URL}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - SLACK_BEARER_TOKEN=${SLACK_BEARER_TOKEN}
    entrypoint: [python, main.py]


